config/routes.rb
Rails.application.routes.draw do

  get 'cart', to: 'carts#show'
  get 'store/index'
  get 'clear', to: 'carts#destroy'
  get '/remove/:id', to: 'line_items#destroy', as: 'remove'

  resources :products
  resources :carts
  resources :line_items
  root "store#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item
  end

end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, :description, :image_url, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: { with: %r{\.(gif|jpg|png)\z}i, message: 'must be a URL for GIF, JPG or PNG' }
  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item

  private

  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, 'Line Items present')
      throw :abort
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ show edit update destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    Cart.destroy(session[:cart_id])
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_index_url, notice: "Košík vyprázdněn" }
    end
    reset_session
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find_by(id: session[:cart_id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart
      redirect_to store_index_url, notice: "Špatný košík"
    end
end

app/controllers/concerns/current_cart.rb
module CurrentCart
  private
  def set_cart
    @cart = Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    @cart = Cart.create
    session[:cart_id] = @cart.id
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:create]
  before_action :set_line_item, only: %i[ show edit update ]

  # GET /line_items or /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1 or /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items or /line_items.json
  def create
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item.cart, notice: "Zboží bylo přidáno do košíku" }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1 or /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to line_item_url(@line_item), notice: "Položka byla aktualizována" }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1 or /line_items/1.json
  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy!

    respond_to do |format|
      format.html { redirect_to root_url, notice: "Položka byla úspěšně smazána" }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.text-justify: inter-word !important
    def line_item_params
      params.require(:line_item).permit(:product_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        puts @product.errors.full_messages
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @products = Product.order(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper

  def total_price #sums prices of all products in the basket
    total = 0
    @cart.line_items.each do |item|
      total = total + item.product.price * item.quantity
    end
    total
  end

  def cart_empty?
    !current_cart.nil?
  end

  def current_cart
    if (cart_id = session[:cart_id])
      cart = Cart.find_by(id: session[:cart_id])
      @current_cart = cart
    end
  end

end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def gravatar(title)
    hash = Digest::MD5.hexdigest(title)
    "https://www.gravatar.com/avatar/#{hash}?d=wavatar"
  end
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/carts/_cart.html.erb
<div id="<%= dom_id cart %>">
</div>

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Show this cart", @cart %> |
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Carts</h1>

<div id="carts">
  <% @carts.each do |cart| %>
    <%= render cart %>
    <p>
      <%= link_to "Show this cart", cart %>
    </p>
  <% end %>
</div>

<%= link_to "New cart", new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/show.html.erb
<% if notice %>
  <aside id="notice bg-primary"><%= notice %></aside>
<% end %>
<h2>Košík</h2>
<div style="float: right">Celková cena: <%= number_to_currency(total_price, unit: "Kč", format: "%n %u") %></div>
<br>
<div style="float: right"><%= link_to "Vyklidit košík", clear_path, method: :get, class: "nav-link" %> </div>

<table class="table text-white">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Název</th>
    <th scope="col">Cena</th>
    <th scope="col">Možnosti</th>
    <th scope="col">Počet</th>
  </tr>
  </thead>
  <tbody>
    <%= render(@cart.line_items) %>
  </tbody>
</table>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-dark sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand"><h2 class="text-white">Bruhod</h2></a>
    <button class="navbar-toggler col-md-2 bg-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      Menu
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="nav navbar-nav ml-auto">
        <li class="nav-item"><%= link_to "Produkty", store_index_url, { :class => "nav-link" } %></li>
      </ul>
      <ul class="nav navbar-nav ml-auto ms-auto">
          <h4>
            <% if cart_empty? %>
              <li class="nav-item mr-auto"><%= link_to "Košík", "/cart", { :class => "nav-link" } %></li>
            <% else %>
              <li class="nav-item mr-auto">Prázdný košík</li>
            <% end %>
          </h4>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Depot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-dark text-white">
  <%= render 'layouts/nav' %>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/line_items/_form.html.erb
<%= form_with(model: line_item) do |form| %>
  <% if line_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
        <% line_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.text_field :product_id %>
  </div>

  <div>
    <%= form.label :cart_id, style: "display: block" %>
    <%= form.text_field :cart_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<tr>
  <td><%= image_tag(gravatar(line_item.product.title)) %></td>
  <td><%= line_item.product.title %></td>
  <td><%= number_to_currency(line_item.product.price, unit: "Kč", format: "%n %u") %></td>
  <td><%= link_to "Smazat", remove_path(line_item), method: :get %></td>
  <td><%= line_item.quantity %></td>
</tr>

app/views/line_items/edit.html.erb
<h1>Editing line item</h1>

<%= render "form", line_item: @line_item %>

<br>

<div>
  <%= link_to "Show this line item", @line_item %> |
  <%= link_to "Back to line items", line_items_path %>
</div>

app/views/line_items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Line items</h1>

<div id="line_items">
  <% @line_items.each do |line_item| %>
    <%= render line_item %>
    <p>
      <%= link_to "Show this line item", line_item %>
    </p>
  <% end %>
</div>

<%= link_to "New line item", new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line item</h1>

<%= render "form", line_item: @line_item %>

<br>

<div>
  <%= link_to "Back to line items", line_items_path %>
</div>

app/views/line_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @line_item %>
<div>
  <%= link_to "Edit this line item", edit_line_item_path(@line_item) %> |
  <%= link_to "Back to line items", line_items_path %>

  <%= button_to "Destroy this line item", @line_item, method: :delete %>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, "Název", style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, "Popis" ,style: "display: block" %>
    <%= form.text_area :description, rows: 10, cols: 60 %>
  </div>

  <div>
    <%= form.label :image_url, style: "display: block" %>
    <%= form.text_field :image_url %>
  </div>

  <div>
    <%= form.label :price, "Cena" ,style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit "Uložit produkt" %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Název:</strong>
    <%= product.title %>
  </p>

  <p>
    <strong>Popis:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Image url:</strong>
    <%= product.image_url %>
  </p>

  <p>
    <strong>Cena:</strong>
    <%= product.price %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<% if notice %>
  <aside id="notice"><%= notice %></aside>
<% end %>

<h1>Produkty</h1>
<%= link_to "Nový produkt", new_product_path %>
<table class="table text-white">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Název</th>
    <th scope="col">Popis</th>
    <th scope="col">Image_url</th>
    <th scope="col">Cena</th>
    <th scope="col">Možnosti</th>
  </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
        <tr>
          <td>
            <%= product.id %>
          </td>
          <td class="description">
            <h3><%= product.title %></h3>
          </td>
          <td class="description">
            <p>
              <%= truncate(strip_tags(product.description), length: 80) %>
            </p>
          </td>
          <td>
            <img src="<%= gravatar(product.title) %>">
            <%#= image_tag(product.image_url, class: 'list-image') %>
          </td>
          <td>
            <%= product.price %>
          </td>
          <td class="actions">
            <ul>
              <li><%= link_to 'Zobrazit', product %></li>
              <li><%= link_to 'Upravit', edit_product_path(product) %></li>
              <li>
                <%= link_to 'Smazat', product, method: :delete, data: { confirm: 'Are you sure?' } %>
              </li>
            </ul>
          </td>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h1>Nový produkt</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Zpátky", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Upravit", edit_product_path(@product) %> |
  <%= link_to "Zpátky na seznam", products_path %>

  <%= button_to "Smazat", @product, method: :delete %>
</div>

app/views/store/index.html.erb
<% if notice %>
  <aside id="notice"><%= notice %></aside>
<% end %>

<h1>Katalog</h1>
<% cache @products do %>
  <% @products.each do |product| %>
    <% cache product do %>
      <div class="row border border-warning">
        <h2 class="float-left"><%= product.title %></h2>
        <div class="row">
          <div class="col-md-2">
            <%= image_tag(gravatar(product.title), class: "gravatar-image") %>
          </div>
          <div class="col-md-10 popis">
            <p><%= product.description %></p>
          </div>
          <div class="mt-2 mb-3 ml-3 ml-auto col-md-12 shop-button">
            <%= button_to "Přidat do košíku", line_items_path(product_id: product), class: "btn btn-success float-right shop-col" %>
            <div class="shop-col">
              <%= number_to_currency(product.price, unit: "Kč", format: "%n %u") %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>